project:
  type: book
  output-dir: docs

book:
  title: "Markup Languages and Reproducible Programming in Statistics"
  repo-url: https://github.com/gerkovink/markup
  repo-branch: dev
  repo-actions: [edit, issue]
  author: 
  - name: Gerko Vink
    orcid: 0000-0001-9767-1924
    email: g.vink@uu.nl
    # affiliations: 
    # - name: ""
  - name: Hanne Oberman
    orcid: 0000-0003-3276-2141
    email: h.i.oberman@uu.nl
    # affiliations: 
    # - name: 
  date: last-modified
  chapters:
    - index.qmd
    - overview.qmd
    - team.qmd
    - deliverables.qmd
    - genai.qmd
    - week 1.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    toc-depth: 3
    include-after-body: custom.html
    theme: cosmo
  pdf:
    documentclass: scrreprt



